"""create order table

Revision ID: 34efb06276c6
Revises: 
Create Date: 2026-07-24 11:04:49.358473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34efb06276c6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS orders")
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'PREPARING', 'READY', 'OUT_FOR_DELIVERY', 'DELIVERED', 'CANCELLED', name='order_status', schema="orders"), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='orders'
    )
    op.create_index('ix_orders_customer_id', 'orders', ['customer_id'], unique=False, schema='orders')
    op.create_index('ix_orders_restaurant_id', 'orders', ['restaurant_id'], unique=False, schema='orders')
    op.create_index('ix_orders_status', 'orders', ['status'], unique=False, schema='orders')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_orders_status', table_name='orders', schema='orders')
    op.drop_index('ix_orders_restaurant_id', table_name='orders', schema='orders')
    op.drop_index('ix_orders_customer_id', table_name='orders', schema='orders')
    op.drop_table('orders', schema='orders')
    op.execute("DROP SCHEMA IF EXISTS orders CASCADE")
    # ### end Alembic commands ###
