"""add idempotency keys

Revision ID: a838cf8010a6
Revises: 34efb06276c6
Create Date: 2026-07-27 21:30:59.110981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a838cf8010a6'
down_revision: Union[str, Sequence[str], None] = '34efb06276c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idempotency_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key'),
    schema='orders'
    )
    op.create_index('ix_idempotency_keys_key', 'idempotency_keys', ['key'], unique=False, schema='orders')
    op.create_index('ix_idempotency_keys_order_id', 'idempotency_keys', ['order_id'], unique=False, schema='orders')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_idempotency_keys_order_id', table_name='idempotency_keys', schema='orders')
    op.drop_index('ix_idempotency_keys_key', table_name='idempotency_keys', schema='orders')
    op.drop_table('idempotency_keys', schema='orders')
    # ### end Alembic commands ###
